version: 0.0
os: linux
files:
  - source: /app/drupal/
    destination: /home/bitnami/stack/drupal/
    file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/rmoldsite.sh
      timeout: 300
      runas: root
    - location: scripts/install_dependencies
      timeout: 300
    #  runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

