#!/bin/bash
sudo apt install php-all-dev
sudo apt install php-intl
sudo apt install php-mbstring
curl -s https://getcomposer.org/installer | php
mv composer.phar ~/.local/bin/composer
cd /app/drupal
composer install -n
